version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: miladev@pc00541  
      MYSQL_DATABASE: vchat_db         
      MYSQL_USER: miladev                  
      MYSQL_PASSWORD: miladev@pc00541       
    ports:
      - "3306:3306"                       
    volumes:
      - mysql_data:/var/lib/mysql         

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql                     
      PMA_PORT: 3306
      PMA_USER: root                      
      PMA_PASSWORD: miladev@pc00541          
    ports:
      - "8080:80"                          
    depends_on:
      - mysql

volumes:
  mysql_data:
